version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api  # Replace with the actual name of your API Dockerfile
    container_name: combis-api
    ports:
      - "5000:80"  # Expose the API on port 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge